name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_KEY }}" | docker login -u 'hnudka' --password-stdin
        docker build . --file Dockerfile --tag html-test:$(date +%s)
        docker push html-test:$(date +%s)
        
      
