name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set current date as env variable
      run: echo "VERSION=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $VERSION
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_KEY }}" | docker login -u 'hnudka' --password-stdin
        docker build -t hnudka/html-test:$VERSION .
        docker push hnudka/html-test:$VERSION
    - name: Run finish
      run: |
        while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "20.04"), sep = "\n")')
